sources:
  nofluffjobs:
    host: nofluffjobs.com
    rootPath: /api/posting
    port: 443
    scheme: https
    categories: backend, frontend, fullstack, projectmanager
    cities: warsaw
currencies:
  base: PLN
  conversions:
    EUR: 4.37
    USD: 4.07
    GBP: 5.1
# add machine-specific properties to application-default.yml
